apiVersion : apps/v1
kind: Deployment
metadata:
  name: "globoticketcluster-4831"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "globoticketcluster-4831"
  template:
    metadata:
      labels:
        app: "globoticketcluster-4831"
    spec:
      containers:
        - name: "globoticketcluster-4831"
          image: "farnamacr.azurecr.io/globoticketcluster"
          ports:
          - containerPort: 80