on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: farnamacr.azurecr.io
        username: ${{ secrets.acr_farnamacr_username }}
        password: ${{ secrets.acr_farnamacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t farnamacr.azurecr.io/globoticketcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push farnamacr.azurecr.io/globoticketcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_globoticketcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep farnamtest | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace farnamtest`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: farnamtest
        container-registry-url: farnamacr.azurecr.io
        container-registry-username: ${{ secrets.acr_farnamacr_username }}
        container-registry-password: ${{ secrets.acr_farnamacr_password }}
        secret-name: globoticketcdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: farnamtest
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          farnamacr.azurecr.io/globoticketcluster:${{ github.sha }}
        imagepullsecrets: |
          globoticketcdockerauth
